"""add_moms_and_action_items_tables

Revision ID: 14a5bc355b56
Revises: 351fe9c66420
Create Date: 2026-02-12 20:49:49.123282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a5bc355b56'
down_revision: Union[str, None] = '351fe9c66420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_title', sa.String(length=300), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moms_document_id'), 'moms', ['document_id'], unique=True)
    op.create_table('action_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mom_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='actionitempriority'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='actionitemstatus'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mom_id'], ['moms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_mom_id'), 'action_items', ['mom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_mom_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_moms_document_id'), table_name='moms')
    op.drop_table('moms')
    # ### end Alembic commands ###
