"""add_products_quotations_tables

Revision ID: 351fe9c66420
Revises: e3fd8111e551
Create Date: 2026-02-05 22:20:11.725442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351fe9c66420'
down_revision: Union[str, None] = 'e3fd8111e551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('default_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('gst_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_gst', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('igst_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_document_id'), 'quotations', ['document_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('gst_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('is_free_text', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_quotations_document_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
