"""Add default terms and conditions

Revision ID: cb74972ebf91
Revises: fa7b61f69e13
Create Date: 2026-03-30 13:08:51.239088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb74972ebf91'
down_revision: Union[str, None] = 'fa7b61f69e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'draft_data')
    op.add_column('users', sa.Column('default_terms_conditions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_terms_conditions')
    op.add_column('documents', sa.Column('draft_data', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
