"""increase audit_log entity_id length

Revision ID: e3fd8111e551
Revises: 3dba1013dc53
Create Date: 2026-02-04 22:12:31.979292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3fd8111e551'
down_revision: Union[str, None] = '3dba1013dc53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entity_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
