"""Add GST toggle and manual total to Quotation

Revision ID: fa7b61f69e13
Revises: a1f23c456d78
Create Date: 2026-03-03 12:57:15.455246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7b61f69e13'
down_revision: Union[str, None] = 'a1f23c456d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('is_gst_on', sa.Boolean(), nullable=True))
    op.add_column('quotations', sa.Column('manual_total_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'manual_total_amount')
    op.drop_column('quotations', 'is_gst_on')
    # ### end Alembic commands ###
